keys:
  - &hera age18rdmsp0nmh45hehn23fh5p4k8pqptj84kaqtfk4a0w0k7c47npgqrdnayx
  - &toolbx age1cekzgm4ws6dry2gfsy9dsm6k0fqprzhq90l6qrz35whm7wk394ws53czcm

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *hera
          - *toolbx